name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build20:
    name: Build C++ 20
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build basic
      run: g++ -std=c++20 -fpermissive src/TinyJSON.cpp example/basic_parse.cpp -o basic_parse

    - name: run basic
      run: |
        set +e
        ./basic_parse

    - name: build options
      run: g++ -std=c++20 -fpermissive src/TinyJSON.cpp example/options.cpp -o options

    - name: run otpions
      run: |
        set +e
        ./options

  build11:
    name: Build C++ 11
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build options c++11
      run: g++ -std=c++11 -fpermissive src/TinyJSON.cpp example/options11.cpp -o options11

    - name: run otpions11  
      run: |
        set +e
        ./options11
