name: I/O Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test_io_linux:
    name: Build and Test I/O Examples (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build JSON C++11
      run: g++ -std=c++11 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json.cpp -o rw_json_11

    - name: run JSON C++11
      run: ./rw_json_11

    - name: build JSON5 C++11
      run: g++ -std=c++11 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json5.cpp -o rw_json5_11

    - name: run JSON5 C++11
      run: ./rw_json5_11

    - name: build JSON C++20
      run: g++ -std=c++20 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json.cpp -o rw_json_20

    - name: run JSON C++20
      run: ./rw_json_20

    - name: build JSON5 C++20
      run: g++ -std=c++20 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json5.cpp -o rw_json5_20

    - name: run JSON5 C++20
      run: ./rw_json5_20

  test_io_macos:
    name: Build and Test I/O Examples (macOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: build JSON C++11
      run: g++ -std=c++11 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json.cpp -o rw_json_11

    - name: run JSON C++11
      run: ./rw_json_11

    - name: build JSON5 C++11
      run: g++ -std=c++11 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json5.cpp -o rw_json5_11

    - name: run JSON5 C++11
      run: ./rw_json5_11

    - name: build JSON C++20
      run: g++ -std=c++20 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json.cpp -o rw_json_20

    - name: run JSON C++20
      run: ./rw_json_20

    - name: build JSON5 C++20
      run: g++ -std=c++20 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json5.cpp -o rw_json5_20

    - name: run JSON5 C++20
      run: ./rw_json5_20

  test_io_windows:
    name: Build and Test I/O Examples (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        release: true
        install: >-
          mingw-w64-x86_64-gcc

    - name: build and run JSON C++11
      shell: msys2 {0}
      run: |
        g++ -std=c++11 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json.cpp -o rw_json_11.exe
        ./rw_json_11.exe

    - name: build and run JSON5 C++11
      shell: msys2 {0}
      run: |
        g++ -std=c++11 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json5.cpp -o rw_json5_11.exe
        ./rw_json5_11.exe

    - name: build and run JSON C++20
      shell: msys2 {0}
      run: |
        g++ -std=c++20 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json.cpp -o rw_json_20.exe
        ./rw_json_20.exe

    - name: build and run JSON5 C++20
      shell: msys2 {0}
      run: |
        g++ -std=c++20 -Wall -Wextra -Werror -O3 src/TinyJSON.cpp example/read_write_json5.cpp -o rw_json5_20.exe
        ./rw_json5_20.exe
